[package]
name = "day11part2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.7.0"
recap = "0.1.2"
serde = "1.0.149"
serde_with = "2.1.0"
num-integer = "0.1.45"
